name: Deploy to EC2 (Stage)

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2-1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd journey-dev
            git pull origin stage
            mvn clean package
            pkill java || true
            nohup java -jar target/*.jar > app.log 2>&1 &

      - name: Deploy to EC2-2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd journey-dev
            git pull origin stage
            mvn clean package
            pkill java || true
            nohup java -jar target/*.jar > app.log 2>&1 &